# -*- eval: (visual-line-mode 1) -*-
#+STARTUP: showall

* org-inline-pdf

Org-inline-pdf enables inline PDF preview in Org buffers.

** Installation

This works only with Org 9.4 or later. You need to have [[https://cityinthesky.co.uk/opensource/pdf2svg/][pdf2svg]] installed in ~exec-path~.

Download org-inline-pdf.el into somewhere in your local directory and install it with the following.

#+BEGIN_SRC emacs-lisp
(package-install-file "/path-to-download-dir/org-inline-pdf.el")
#+END_SRC

Require it in your init file to enable it at startup.

#+BEGIN_SRC emacs-lisp
(require 'org-inline-pdf)
#+END_SRC

** Usage

You can just place links to PDF files using double brackets like ~[[./figs/plot.pdf]]~ in Org buffers. Linked PDF files will be displayed inline in the Org buffer by ~org-display-inline-images~ command.

*** Inline PDF in exported HTML file

This package also makes Org's HTML exporter ox-html to embed linked PDF files as images using ~img~ tag. Note that inline PDF using img tag is not standard and will be rendered only in particular browsers.  Safari.app is only the one I know.
