# -*- eval: (visual-line-mode 1) -*-
#+STARTUP: showall

[[https://melpa.org/#/org-inline-pdf][file:https://melpa.org/packages/org-inline-pdf-badge.svg]] [[https://stable.melpa.org/#/org-inline-pdf][file:https://stable.melpa.org/packages/org-inline-pdf-badge.svg]]

* org-inline-pdf

Org-inline-pdf enables inline PDF preview in Org buffers.

** Installation

This works only with Org 9.4 or later. You need to have [[https://cityinthesky.co.uk/opensource/pdf2svg/][pdf2svg]] installed in =exec-path=.

You can install this package from MELPA. The package name is =org-inline-pdf=. For manual installation, download org-inline-pdf.el into somewhere in your local directory and install it with ~M-x package-install-file~.

Enable this feature in an Org buffer with ~M-x org-inline-pdf-mode~. Add the following line in your init file to automatically enable the feature in newly opened Org buffers.

#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook #'org-inline-pdf-mode)
#+END_SRC

** Usage

You can just place links to PDF files using double brackets like =[[./figs/plot.pdf]]= in Org buffers. Linked PDF files will be displayed inline in the Org buffer by =org-display-inline-images= command.

*** Inline PDF in exported HTML file

This package also makes Org's HTML exporter ox-html to embed linked PDF files as images using =img= tag. Note that inline PDF using img tag is not standard and will be rendered only in particular browsers.  Safari.app is only the one I know.
